### ISSUE TITLE
extract got stuck 

### ISSUE THREAD

**Issue by zsokolowski** [quiris11/ExtractCoverThumbs#1]
- Processing "Beyond Legacy Code, P1.0 (Zbigniew Sokołowski).azw3_C9BFA7F1684645929AA45FCB5CC6974F.azw3": Extracting Cover Thumb: 

and then stops for ever on this ebook

**Comment by zsokolowski** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyo", line 1470, in **call**
  File "gui.py", line 163, in run
  File "ExtractCoverThumbs.pyo", line 193, in extract_cover_thumbs
  File "ExtractCoverThumbs.pyo", line 62, in get_cover_image
  File "PIL\Image.pyo", line 2106, in open
  File "PIL\ImageFile.pyo", line 92, in **init**
  File "PIL\BmpImagePlugin.pyo", line 174, in _open
  File "PIL\BmpImagePlugin.pyo", line 100, in _bitmap
IOError: Unsupported BMP header type (2264)
